### PR TITLE
weighted CN

### PR DESCRIPTION
**Pull request by iembry**
Hi @cvitolo  I have created the pull request. I created the function weighted_CN.R and I updated the DESCRIPTION file due to package requirements in the new function. I did not write any testthat tests for the function, but I did include some error checking within the function.

Thank you.

Irucka

### CODE REVIEW

**Comment by cvitolo** [comment]
Many thanks Irucka, much appreciated!

**Comment by iembry** [comment]
Hi @cvitolo  Are you going to accept the pull request (merge the weighted_CN with your R code)?

Thank you.

Irucka

**Comment by cvitolo** [comment]
I have already done it ;)

**Comment by iembry** [comment]
Hi @cvitolo  Thank you for letting me know. :)

I have made some revisions to DESCRIPTION (added `ramify` as a Suggested package) and to the weighted_CN function (added 2 more examples and made sure that the unit conversion is accurate). Thank you.

Irucka

**Pull request closed without merging**
